version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./etc/nginx/log.template.conf:/var/log/nginx/"
      - "./etc/ssl:/etc/ssl"
      - "./html:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
      - mariadb
      - sphinx

  mariadb:
    image: mariadb:${MYSQL_VERSION}
    restart: on-failure
    env_file:
      - ".env"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"

  php:
    image: php:${PHP_VERSION}-fpm
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./html:/var/www/html"
    ports:
      - "9000:9000"
    build:
      context: ./etc/php
      dockerfile: ./Dockerfile

  sphinx:
    image: stefobark/sphinxdocker
    restart: always
    volumes:
      - ./etc/sphinx/config:/etc/sphinxsearch
      - ./etc/sphinx/:/var/lib/sphinxsearch
      - ./data/sphinx:/home/sphinx
    ports:
      - "9306:9306"
      - "9312:9312"
    build:
      context: ./etc/sphinx
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb

