<?php
$menu["menu300"] = array (
    array("300000", "상품 관리", ""),
	array("300100", "상품관리", "$g4[shop_admin_path]/itemlist.php"),
	array("300200", "목록통관상품관리", "$g4[shop_admin_path]/list_clearance_item.php"),
	array("300300", "1회구매수량관리", "$g4[shop_admin_path]/item_order_onetime_limit_list.php"),
	array("300320", "상품병수량관리", "$g4[shop_admin_path]/item_health_cnt.php"),
	//array("300340", "품절상품관리", "$g4[shop_admin_path]/item_soldout_list.php"),
	array("300360", "품절상품관리", "$g4[shop_admin_path]/item_stock_in.php"),
	array("300380", "상품품절처리", "$g4[shop_admin_path]/item_stock_out.php"),
	array("300400", "품절히스토리", "$g4[shop_admin_path]/item_stock_history.php"),
	array("300420", "단종상품관리", "$g4[shop_admin_path]/item_discont_list.php"),	
	array("300500", "<span style='color:#FF6600;'>제조사 설명관리</span>", "$g4[shop_admin_path]/item_maker_description.php"),
	array("300600", "상품유형관리", "$g4[shop_admin_path]/itemtypelist.php"),
    //array("300700", "상품재고관리", "$g4[shop_admin_path]/itemstocklist.php"),
	array("300800", "사용후기", "$g4[shop_admin_path]/itempslist.php"),    
	array("300840", "베스트 상품 수동 등록", "$g4[shop_admin_path]/best_item_reg.php"),
	array("300860", "별도 재고관리 상품", "$g4[shop_admin_path]/event_item_stock.php"),
	array("300880", "클리어런스 상품", "$g4[shop_admin_path]/clearance_list.php"),
	array("300900", "아이해피 상품 수동등록", "$g4[shop_admin_path]/ihappy_item_manual_reg.php"),
	array("300920", "아이허브 가격 수집 상품 관리", "$g4[shop_admin_path]/iherb_price_manager.php"),
	array("300940", "상품입고 SMS관리", "$g4[shop_admin_path]/item_sms_list.php"),
	array("300960", "상품코드관리", "$g4[shop_admin_path]/itemcode_manager.php"),
	array("300970", "상품후기 입력", "$g4[shop_admin_path]/item_review_write.php"),
	array("300110", "상품매핑", "$g4[shop_admin_path]/item_mapping.php"),
	array("300120", "NFO WEB", "$g4[shop_admin_path]/nfo.php"),
	array("300140", "단종 판매중 상품 관리", "$g4[shop_admin_path]/discontinued_sales_item.php"),
	array("300150", "UPC 상품 검색", "$g4[shop_admin_path]/upc_search.php"),
	array("300160", "상품 문구 삽입", "$g4[shop_admin_path]/commnet_insert.php"),
	array("300170", "사은품추가", "$g4[shop_admin_path]/payment_insert.php"),
	array("300999", "세트상품 생성", "$g4[shop_admin_path]/set_item_view.php"),
    array("300567", "세트상품 상세설명등록", "$g4[shop_admin_path]/set_item_info_list.php"),
	array("300888", "관별 TOP100 리스트", "$g4[shop_admin_path]/top100_list.php"),
    array("300666", "신상품 카테고리 관리", "$g4[shop_admin_path]/no_new_item.php"),
    array("300777", "상품입고요청관리", "$g4[shop_admin_path]/item_onrequest_list.php"),
    array("300123", "비가공식품관리", "$g4[shop_admin_path]/item_weight_list.php"),
    array("300667", "비가공식품종류관리", "$g4[shop_admin_path]/item_weight_type_list.php"),
    array("300124", "다중세트상품 단품가 관리", "$g4[shop_admin_path]/set_item_amount_list.php"),
    array("300125", "상품 일괄 상태 변경", "$g4[shop_admin_path]/item_status_change.php"),
    array("300126", "전체 상품 가격 리스트", "$g4[shop_admin_path]/all_product_price_list.php"),
    array("300127", "상품 MSRP 입력/수정", "$g4[shop_admin_path]/product_msrp_list.php"),
    array("300770", "네이버CPS 상품관리", "$g4[shop_admin_path]/naver_cps_item.php"),

);
